apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: v5elvpoxn-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: v5elvpoxn-nodejs 
  name: v5elvpoxn-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: v5elvpoxn-nodejs 
